import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Auto-generated sidebar from skills.ts
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Run: npx tsx scripts/generate-sidebar.ts
 *
 * This sidebar is automatically generated from src/data/skills.ts
 * to ensure it stays in sync with the skills gallery.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/claude-skills-guide',
        'guides/prompt-learning-mcp',
        'guides/examples',
        'guides/skills-documentation',
      ],
    },
    {
      type: 'category',
      label: 'Orchestration & Meta',
      collapsed: false,
      items: [
        'skills/orchestrator',
        'skills/agent_creator/agent_creator',
        'skills/skill_coach/skill_coach',
        'skills/skill_documentarian/skill_documentarian',
        'skills/swift_executor',
        'skills/automatic_stateful_prompt_improver/automatic_stateful_prompt_improver',
      ],
    },
    {
      type: 'category',
      label: 'Visual Design & UI',
      collapsed: false,
      items: [
        'skills/web_design_expert/web_design_expert',
        'skills/design_system_creator',
        'skills/native_app_designer/native_app_designer',
        'skills/vaporwave_glassomorphic_ui_designer/vaporwave_glassomorphic_ui_designer',
        'skills/windows_3_1_web_designer/windows_3_1_web_designer',
        'skills/typography_expert',
        'skills/vibe_matcher',
        'skills/interior_design_expert/interior_design_expert',
        'skills/design_archivist/design_archivist',
      ],
    },
    {
      type: 'category',
      label: 'Graphics, 3D & Simulation',
      collapsed: false,
      items: [
        'skills/metal_shader_expert/metal_shader_expert',
        'skills/vr_avatar_engineer',
        'skills/physics_rendering_expert/physics_rendering_expert',
        'skills/collage_layout_expert/collage_layout_expert',
        'skills/2000s_visualization_expert',
      ],
    },
    {
      type: 'category',
      label: 'Audio & Sound Design',
      collapsed: false,
      items: [
        'skills/sound_engineer/sound_engineer',
        'skills/voice_audio_engineer/voice_audio_engineer',
      ],
    },
    {
      type: 'category',
      label: 'Computer Vision & Image AI',
      collapsed: false,
      items: [
        'skills/clip_aware_embeddings',
        'skills/photo_content_recognition_curation_expert/photo_content_recognition_curation_expert',
        'skills/event_detection_temporal_intelligence_expert/event_detection_temporal_intelligence_expert',
        'skills/photo_composition_critic/photo_composition_critic',
        'skills/color_theory_palette_harmony_expert/color_theory_palette_harmony_expert',
      ],
    },
    {
      type: 'category',
      label: 'Autonomous Systems & Robotics',
      collapsed: false,
      items: [
        'skills/drone_cv_expert/drone_cv_expert',
        'skills/drone_inspection_specialist/drone_inspection_specialist',
      ],
    },
    {
      type: 'category',
      label: 'Conversational AI & Bots',
      collapsed: false,
      items: [
        'skills/bot_developer/bot_developer',
      ],
    },
    {
      type: 'category',
      label: 'Research & Strategy',
      collapsed: false,
      items: [
        'skills/research_analyst',
        'skills/team_builder',
        'skills/competitive_cartographer/competitive_cartographer',
        'skills/hr_network_analyst/hr_network_analyst',
        'skills/indie_monetization_strategist',
        'skills/seo_visibility_expert',
      ],
    },
    {
      type: 'category',
      label: 'Coaching & Personal Development',
      collapsed: false,
      items: [
        'skills/career_biographer',
        'skills/cv_creator/cv_creator',
        'skills/job_application_optimizer',
        'skills/personal_finance_coach/personal_finance_coach',
        'skills/tech_entrepreneur_coach_adhd/tech_entrepreneur_coach_adhd',
        'skills/project_management_guru_adhd/project_management_guru_adhd',
        'skills/jungian_psychologist/jungian_psychologist',
        'skills/wisdom_accountability_coach/wisdom_accountability_coach',
        'skills/hrv_alexithymia_expert/hrv_alexithymia_expert',
        'skills/speech_pathology_ai/speech_pathology_ai',
        'skills/adhd_design_expert/adhd_design_expert',
      ],
    },
    {
      type: 'category',
      label: 'DevOps & Site Reliability',
      collapsed: false,
      items: [
        'skills/site_reliability_engineer/site_reliability_engineer',
        'skills/code_necromancer/code_necromancer',
      ],
    },
  ],
};

export default sidebars;
